[jobs.lab1]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]

[jobs.lab2]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]

[jobs.lab3]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]

[jobs.lab4]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]

[jobs.lab5]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]

[jobs.lab6]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]

[jobs.lab7]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]

[jobs.lab8]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]

[jobs.mem2reg]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]

[jobs.short_circuit]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]

[jobs.mdarray]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]

[jobs.inline]

image = { source = "dockerfile", path = "."}

run = [
  "java App $input $ir",
]